spring:
  security:
    enable-csrf: false
    enable: false
  application:
    name: monomer
  datasource:
    druid:
      name: monomer
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      enable: true
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/monomer?serverTimezone=GMT%2B8
      defaultAutoCommit: false
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 10000
      filters: stat,wall
      useGlobalDataSourceStat: true
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      #password: Ambow99999999
      timeout: 3600
      lettuce:
        pool:
          min-idle: 10
          max-active: 10
          max-idle: 20
          max-wait: 6000
  profiles:
    active:
    - dev

server:
  max-http-header-size: 100MB
  http2:
    enabled: true

mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      table-prefix: t_
      table-underline: true

logging:
  level:
    ROOT: INFO
  config: classpath:logback-monomer.xml
  path: ./logs/monomer
