spring:
  datasource:    hikari:      username: root
      password: 123456
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test
      auto-commit: false
      driver-class-name: com.mysql.jdbc.Driver
  profiles:    active:    - dev

server:
  max-http-header-size: 100MB
  http2:
    enabled: true